### ISSUE TITLE
Cooperate to improve CodeAssist?

### ISSUE THREAD

**Issue by davidschachter** [Deenu488/CodeAssist-Unofficial#16]
Hi. Would you be willing to chat with me about improvements to CodeAssist? I have time and energy but I don't want to duplicate what you are doing. I'm at davidschachter@gmail.com. Thank you.

**Comment by Tanzin01** [comment]
i can assist too

**Comment by Deenu488** [comment]
Hii, I am come back

**Comment by yaturner** [comment]
would you be available to answer a few question about the functionality of the application

**Comment by Deenu488** [comment]
Yeah ask

**Comment by appdevforall** [comment]
before I start, would you prefer to do this by email rather than github?

**Comment by Deenu488** [comment]
Hii

**Comment by appdevforall** [comment]
I would very much like to add the ability to debug the target application
(Created project) on the phone using adb/jdb, is this something that you
have explored? Do you think it is doable?

**Comment by appdevforall** [comment]
Ok, thanks for the reply. I would also like to look at your code for the
XML preview and the drag and drop interface for adding widgets, where
should I start looking in the code

**Comment by Deenu488** [comment]
@appdevforall layout-preview

**Comment by appdevforall** [comment]
I have made  some commits to my fork of code assist to better support Github

1. added settings for Github user id, email, and auth token
2. added support for authenticator for https clone
3. added code for git commit  and push to show files to be committed etc.
4. added to code to check if the clone directory is empty and if not offer
to empty it before cloning

is any of this of interest to you?

**Comment by Deenu488** [comment]
@appdevforall Auth token, it's new and easy task for cloning

**Comment by yaturner** [comment]
yes I have already coded all of the things I mentioned, I was asking if you
were interested in integrating my code into yours
