### ISSUE TITLE
import project doesn't work

### ISSUE THREAD

**Issue by Tanzin01** [Deenu488/CodeAssist-Unofficial#23]
**Describe the bug**
Whike trying to import a project Can't select folder.  No sign or anything to select with. 
**To Reproduce**
1. Select import project from CA
2. Browser to folder of project via system sile manager

**Expected behavior**
A way to select folder
**Screenshots**

**Smartphone (please complete the following information):**
 - OS: [e.g. iOS8.1] android14
 - 

**Additional context**

**Comment by Deenu488** [comment]
You can't select folder you can import only zip project

**Comment by Tanzin01** [comment]
Ahh, okay. Got it.
