### ISSUE TITLE
Fix error merge?

### ISSUE THREAD

**Issue by truong4484** [Deenu488/CodeAssist-Unofficial#33]
Task :app:clean
> Task :app:formatKotlin
> Task :app:formatJava
> Task :app:checkLibraries
> Task :app:assembleLibraries
> Task :app:mergeManifest
> Task :app:generateDebugBuildConfig
> Task :app:generateFirebaseConfig
> Task :app:injectLogger
> Task :app:crashlytics
> Task :app:mergeResources
> Task :app:generateViewBinding
> Task :app:symbolProcessor
> Task :app:compileKotlin
> Task :app:compileJavaWithJavac
> Task :app:mergeDexWithD8
> DexingWithClasspathTransform 45a1df17846d0e034a2bf46d1f39ad31
ERROR:  java.lang.NoSuchMethodError: No interface method toArray(Ljava/util/function/IntFunction;)[Ljava/lang/Object; in class Ljava/util/List; or its super classes (declaration of 'java.util.List' appears in /apex/com.android.art/javalib/core-oj.jar)
ERROR:  com.android.tools.r8.CompilationFailedException: Compilation failed to complete

**Comment by Deenu488** [comment]
@truong4484 45a1df17846d0e034a2bf46d1f39ad31

Exclude this library 
Or if you have multidex library then remove it
And build again

**Comment by truong4484** [comment]
Thank you!
