### ISSUE TITLE
No Issue, but see

### ISSUE THREAD

**Issue by trindadedev13** [Deenu488/CodeAssist-Unofficial#36]
hey @Deenu488, see [My Fork Pulls](https://github.com/trindadedev13/CodeAssist-Unofficial/pulls) here have 52 PR's of MendRenovateBot, and this will take time to merge since you have automerge disabled

**Comment by Deenu488** [comment]
@trindadedev13 I am not familiar with the bot I checked and accepted it
But when I merged they are automatically merging so I disabled it

**Comment by trindadedev13** [comment]
@Deenu488 Well, anyway, I'll merge the PRs one by one, and open a new pull request for you.

**Comment by trindadedev13** [comment]
https://github.com/trindadedev13/CodeAssist-Unofficial/actions

much runs
