### ISSUE TITLE
libGdx jni libs missing & Android Manifest issue

### ISSUE THREAD

**Issue by AmirSinaRZ** [Deenu488/CodeAssist-Unofficial#39]
1 - If you create a LibGdx template, android launcher path is wrong in android manifest.
2 - there is no jni libs in the template so the compiled app crashes.

**Comment by AmirSinaRZ** [comment]
Version: 1.0.0
Screenshots:
![AddText_09-11-06 46 13](https://github.com/user-attachments/assets/889d4f49-011e-4386-9bb8-25c9f37ea09a)
![AddText_09-11-06 46 29](https://github.com/user-attachments/assets/d90a46c9-b77a-4e2c-b2f4-f429b7b4c191)
![AddText_09-11-06 46 58](https://github.com/user-attachments/assets/403f16ac-5a03-451c-bf68-7cb1b5283db8)
![AddText_09-11-06 47 20](https://github.com/user-attachments/assets/32094027-3365-44eb-b53c-65c3213d9c6b)

**Comment by AmirSinaRZ** [comment]
There is no lib folder for native libs in compiled Apk

**Comment by Deenu488** [comment]
Download latest version from commits
